plugins {
    id 'com.android.application'
}

android {
    namespace 'com.daycount.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.daycount.app'
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
