plugins {
    id 'com.android.application'
}

android {
    namespace 'com.noiosius.igdm'
    compileSdk 35

    defaultConfig {
        applicationId 'com.noiosius.igdm'
        minSdk 28
        targetSdk 34
        versionCode 12
        versionName '0.12.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
