plugins {
    id 'com.android.application'
}

android {
    namespace 'com.quiethome.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.quiethome.app'
        minSdk 28
        targetSdk 33
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
