plugins {
    id 'com.android.application'
}

android {
    namespace 'com.locktodo.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.locktodo.app'
        minSdk 28
        targetSdk 33
        versionCode 5
        versionName '0.5.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
