plugins {
    id 'com.android.application'
}

android {
    namespace 'com.batterycheck.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.batterycheck.app'
        minSdk 28
        targetSdk 33
        versionCode 7
        versionName '1.4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
